version: '3.8'

services:
  adonis:
    build:
      context: ./  # Le dossier où se trouve ton Dockerfile
      dockerfile: Dockerfile  # Nom du fichier Docker, par défaut c'est "Dockerfile"
    restart: always
    container_name: adonis_app
    volumes:
      - .:/app
      - ./database:/app/database  # pour persister le fichier SQLite
    ports:
      - "3333:3333"
    environment:
      - HOST=0.0.0.0
      - PORT=3333
      - NODE_ENV=development
      - DB_CONNECTION=sqlite
      - DB_DATABASE=./database/database.sqlite
    command: node build/server.js
