version: "3.8"

services:
  aaa_backend:
    container_name: aaa-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5555:3333"
    environment:
      NODE_ENV: production
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/tmp/db.sqlite3
    volumes:
      - ./database:/app/tmp/db.sqlite3  # monte ton dossier local ./database dans le conteneur
