version: '3'

services:
  # db:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: yourpassword
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db-data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "7070:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: yourpassword

  aaa-backend:
    container_name: aaa-backend
    build:
      context: ./  # Le dossier où se trouve ton Dockerfile
      dockerfile: Dockerfile  # Nom du fichier Docker, par défaut c'est "Dockerfile"
    restart: always
    ports:
      - "4444:3333"

# volumes:
#   db-data:
